version: 2.1

orbs:
  python: circleci/python@1.5.0
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m unittest discover -p "*_test.py"
      - run:
          name: Gen coverage
          command: pip install coverage && python -m coverage run --source=amap_api -m unittest discover -p "*_test.py" && python -m coverage xml
      - codecov/upload:
          file: coverage.xml
          flags: unittests
          upload_name: amap-web-service-api

workflows:
  test:
    jobs:
      - test
